disabled_rules:
  - trailing_whitespace
  - line_length
  - function_parameter_count
  - variable_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - R.generated.swift
  - SaudeOdontoUITests
included:
  - ../../Pod/Classes
line_length:
  - 170
  - 200
